# Generated by Django 6.0.5 on 2026-06-03 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='nikies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=100)),
                ('ghymat', models.DecimalField(decimal_places=0, max_digits=10)),
            ],
        ),
    ]
