# Generated by Django 6.0.5 on 2026-06-03 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nike_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nikies',
            name='image',
            field=models.ImageField(default=1, upload_to='nike/'),
            preserve_default=False,
        ),
    ]
