# Generated by Django 6.0.5 on 2026-06-06 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nike_app', '0002_nikies_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=100)),
                ('ghymat', models.DecimalField(decimal_places=0, max_digits=10)),
                ('image', models.ImageField(upload_to='home_products/')),
            ],
        ),
    ]
