# Generated by Django 6.0.5 on 2026-06-06 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nike_app', '0003_homeproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeproduct',
            name='category',
            field=models.CharField(choices=[('men', 'مردانه'), ('women', 'زنانه'), ('kids', 'بچگانه')], default='men', max_length=10),
        ),
    ]
