# Generated by Django 6.0 on 2026-05-23 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kala_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trap',
            name='kode',
            field=models.CharField(max_length=70),
        ),
    ]
