# Generated by Django 6.0 on 2026-05-23 20:06

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kala_app', '0002_alter_trap_kode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='formi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('discribshen', models.TextField()),
                ('images', models.ImageField(upload_to='images/formies')),
                ('my_call', models.CharField(help_text='enter your namber ', max_length=12)),
                ('zaman', models.DateField(default=datetime.datetime(2026, 5, 23, 20, 6, 28, 350817, tzinfo=datetime.timezone.utc))),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='trap',
        ),
    ]
