# Generated by Django 6.0 on 2026-05-24 01:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kala_app', '0003_formi_delete_trap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formi',
            name='zaman',
            field=models.DateField(default=datetime.datetime(2026, 5, 24, 1, 37, 56, 537113, tzinfo=datetime.timezone.utc)),
        ),
    ]
