# Generated by Django 6.0 on 2026-05-24 23:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kala_app', '0004_alter_formi_zaman'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formi',
            name='zaman',
            field=models.DateField(default=datetime.datetime(2026, 5, 24, 23, 27, 54, 849401, tzinfo=datetime.timezone.utc)),
        ),
    ]
