# Generated by Django 6.0 on 2026-05-24 23:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kala_app', '0005_alter_formi_zaman'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formi',
            name='my_call',
            field=models.CharField(help_text='enter your number', max_length=12),
        ),
        migrations.AlterField(
            model_name='formi',
            name='zaman',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
