# Generated by Django 6.0 on 2026-05-25 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kala_app', '0006_alter_formi_my_call_alter_formi_zaman'),
    ]

    operations = [
        migrations.AddField(
            model_name='formi',
            name='Published',
            field=models.BooleanField(default=True),
        ),
    ]
