# Generated by Django 6.0.5 on 2026-05-31 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kala_app', '0007_formi_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formi',
            name='my_call',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
