# Generated by Django 6.0.5 on 2026-06-02 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kala_app', '0009_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='formi',
            name='slog',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
