# Generated by Django 6.0 on 2026-05-25 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='articel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('discribshen', models.TextField()),
                ('images', models.ImageField(upload_to='images/articel')),
            ],
        ),
    ]
