# Generated by Django 6.0.5 on 2026-06-03 23:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='zaman',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
